#pragma once

/*
    This file was auto-generated by Ryzerth's magic optimized FIR script.
    DO NOT EDIT MANUALLY!!!
*/

namespace dsp::multirate::decim {
    const unsigned int fir_64_4_len = 19;
    const float fir_64_4_taps[] = {
        0.0000429609248f,
        0.0004765567633f,
        0.0024957623882f,
        0.0086502620997f,
        0.0224930555988f,
        0.0467176748088f,
        0.0803238710382f,
        0.1168174685032f,
        0.1455785879790f,
        0.1565458506682f,
        0.1455785879790f,
        0.1168174685032f,
        0.0803238710382f,
        0.0467176748088f,
        0.0224930555988f,
        0.0086502620997f,
        0.0024957623882f,
        0.0004765567633f,
        0.0000429609248f,
    };
}
