#pragma once

/*
    This file was auto-generated by Ryzerth's magic optimized FIR script.
    DO NOT EDIT MANUALLY!!!
*/

namespace dsp::multirate::decim {
    const unsigned int fir_8_2_len = 9;
    const float fir_8_2_taps[] = {
        -0.0096855460565f,
        -0.0196926482904f,
        0.0627645107767f,
        0.2740445488509f,
        0.4025398240918f,
        0.2740445488509f,
        0.0627645107767f,
        -0.0196926482904f,
        -0.0096855460565f,
    };
}
