#pragma once

/*
    This file was auto-generated by Ryzerth's magic optimized FIR script.
    DO NOT EDIT MANUALLY!!!
*/

namespace dsp::multirate::decim {
    const unsigned int fir_32_4_len = 17;
    const float fir_32_4_taps[] = {
        0.0002602343386f,
        0.0019197560804f,
        0.0076270554566f,
        0.0212647832351f,
        0.0459374309886f,
        0.0808345515056f,
        0.1191594258092f,
        0.1495554802033f,
        0.1611781123721f,
        0.1495554802033f,
        0.1191594258092f,
        0.0808345515056f,
        0.0459374309886f,
        0.0212647832351f,
        0.0076270554566f,
        0.0019197560804f,
        0.0002602343386f,
    };
}
