#pragma once

/*
    This file was auto-generated by Ryzerth's magic optimized FIR script.
    DO NOT EDIT MANUALLY!!!
*/

namespace dsp::multirate::decim {
    const unsigned int fir_4_2_len = 15;
    const float fir_4_2_taps[] = {
        0.0021282968604f,
        0.0076473554450f,
        0.0006460703751f,
        -0.0368053147543f,
        -0.0516552094180f,
        0.0659607033051f,
        0.2951835298658f,
        0.4189947458581f,
        0.2951835298658f,
        0.0659607033051f,
        -0.0516552094180f,
        -0.0368053147543f,
        0.0006460703751f,
        0.0076473554450f,
        0.0021282968604f,
    };
}
