#pragma once

/*
    This file was auto-generated by Ryzerth's magic optimized FIR script.
    DO NOT EDIT MANUALLY!!!
*/

namespace dsp::multirate::decim {
    const unsigned int fir_128_4_len = 16;
    const float fir_128_4_taps[] = {
        0.0003502294673f,
        0.0025622621714f,
        0.0100604175711f,
        0.0274832811630f,
        0.0576540582560f,
        0.0975667617613f,
        0.1368722747794f,
        0.1615718864375f,
        0.1615718864375f,
        0.1368722747794f,
        0.0975667617613f,
        0.0576540582560f,
        0.0274832811630f,
        0.0100604175711f,
        0.0025622621714f,
        0.0003502294673f,
    };
}
