#pragma once

/*
    This file was auto-generated by Ryzerth's magic optimized FIR script.
    DO NOT EDIT MANUALLY!!!
*/

namespace dsp::multirate::decim {
    const unsigned int fir_32_2_len = 6;
    const float fir_32_2_taps[] = {
        0.0303426484663f,
        0.1557222116669f,
        0.3154225044548f,
        0.3154225044548f,
        0.1557222116669f,
        0.0303426484663f,
    };
}
