#pragma once

/*
    This file was auto-generated by Ryzerth's magic optimized FIR script.
    DO NOT EDIT MANUALLY!!!
*/

namespace dsp::multirate::decim {
    const unsigned int fir_64_2_len = 4;
    const float fir_64_2_taps[] = {
        0.1238512125230f,
        0.3713298898913f,
        0.3713298898913f,
        0.1238512125230f,
    };
}
