#pragma once

/*
    This file was auto-generated by the magic optimized FIR script.
    DO NOT EDIT MANUALLY!!!
*/

namespace dsp::multirate::decim {
    const unsigned int fir_4_2_len = 12;
    const float fir_4_2_taps[] = {
        -0.003856211869499,
        -0.022330421420748,
        -0.042348797151517,
        0.009330574289172,
        0.182544215014523,
        0.363014696342451,
        0.363014696342451,
        0.182544215014523,
        0.009330574289172,
        -0.042348797151517,
        -0.022330421420748,
        -0.003856211869499,
    };
}
