#pragma once

/*
    This file was auto-generated by Ryzerth's magic optimized FIR script.
    DO NOT EDIT MANUALLY!!!
*/

namespace dsp::multirate::decim {
    const unsigned int fir_16_2_len = 6;
    const float fir_16_2_taps[] = {
        0.0314633937131f,
        0.1579813285983f,
        0.3165763689208f,
        0.3165763689208f,
        0.1579813285983f,
        0.0314633937131f,
    };
}
